name:                crud-buckets
version:             0.1.0.0
github:              "jacob-alford/crud-buckets"
license:             MIT
author:              "Jacob Alford"
maintainer:          "jacob@jalf.io"
copyright:           "2021 Jacob Alford"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/crud-buckets#readme>

dependencies:
- base >= 4.7 && < 5
- servant
- servant-server
- warp

library:
  exposed-modules:
    - CrudBuckets.Main
  source-dirs: src

executables:
  crud-buckets-exe:
    main:                crud-buckets.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crud-buckets

tests:
  crud-buckets-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crud-buckets
